feat: added routes layout
dev0x451/employee_mood_frontend pull request #1
Opened 2023-05-18 18:30 UTC by RomanRiyanov

Added layout and routes of base components. Of course, it should be removed as soon as possible.

2023-05-19 05:47 UTC, dev0x451 requested changes

2023-05-19 05:52 UTC, dev0x451 commented on src/index.css
> +  --nav-color: #276CB1;
css переменные чуток не так работают, к примеру:
:root {
  /* Colors */
  --color-primary-100: #f4ebff;
}

далее где-то:

backbround-color: var(--color-primary-100)

2023-05-19 06:19 UTC, RomanRiyanov commented on src/main.tsx
Need to be done

2023-05-19 06:19 UTC, RomanRiyanov commented on src/components/App/App.tsx
> +export default App
Done

2023-05-19 06:19 UTC, RomanRiyanov commented on src/index.css
> +  --nav-color: #276CB1;
Done

2023-05-20 13:40 UTC, dev0x451 approved these changes

2023-05-20 13:40 UTC, merged